export const PLANS = [
  {
    id: 'plan-30',
    name: '30-day plan',
    days: 30,
    rate: 0.79,
    allocations: [
      { name: 'Gold', category: 'Commodities', weight: 14 },
      { name: 'Oil', category: 'Commodities', weight: 9 },
      { name: 'Electricity', category: 'Energy', weight: 12 },
      { name: 'S&P 500', category: 'US equities', weight: 19 },
      { name: 'NASDAQ', category: 'Technology equities', weight: 14 },
      { name: 'Tesla', category: 'Individual stocks', weight: 8 },
      { name: 'Artificial intelligence', category: 'Technology', weight: 12 },
      { name: 'Bitcoin', category: 'Crypto', weight: 7 },
      { name: 'Ethereum', category: 'Crypto', weight: 5 },
    ],
  },
  {
    id: 'plan-60',
    name: '60-day plan',
    days: 60,
    rate: 1.14,
    allocations: [
      { name: 'Gold', category: 'Commodities', weight: 10 },
      { name: 'Oil', category: 'Commodities', weight: 9 },
      { name: 'Electricity', category: 'Energy', weight: 10 },
      { name: 'S&P 500', category: 'US equities', weight: 18 },
      { name: 'NASDAQ', category: 'Technology equities', weight: 16 },
      { name: 'Tesla', category: 'Individual stocks', weight: 10 },
      { name: 'Artificial intelligence', category: 'Technology', weight: 15 },
      { name: 'Bitcoin', category: 'Crypto', weight: 7 },
      { name: 'Ethereum', category: 'Crypto', weight: 5 },
    ],
  },
  {
    id: 'plan-90',
    name: '90-day plan',
    days: 90,
    rate: 1.59,
    allocations: [
      { name: 'Gold', category: 'Commodities', weight: 8 },
      { name: 'Oil', category: 'Commodities', weight: 8 },
      { name: 'Electricity', category: 'Energy', weight: 8 },
      { name: 'S&P 500', category: 'US equities', weight: 17 },
      { name: 'NASDAQ', category: 'Technology equities', weight: 18 },
      { name: 'Tesla', category: 'Individual stocks', weight: 10 },
      { name: 'Artificial intelligence', category: 'Technology', weight: 17 },
      { name: 'Bitcoin', category: 'Crypto', weight: 8 },
      { name: 'Ethereum', category: 'Crypto', weight: 6 },
    ],
  },
];
